### PR TITLE
Allow Custom marshallers with ChainedConverterConfiguration

### PR DESCRIPTION
**Pull request by joemccall86**
Fixes https://github.com/grails-plugins/grails-plugin-converters/issues/10

* Add spec for registering marshallers post-configuration
* Update spock dependency to 1.1
* Add grails testing support to include plugins in unit tests
* Ensure custom marshaller registration does not blow away existing chained converter configuration

### CODE REVIEW

**Comment by jameskleeh** [comment]
@joemccall86 I appreciate the work put into this PR, however this plugin has been deprecated and is unlikely to see a new release

**Comment by joemccall86** [comment]
I'm happy to help where I can. I understand the need to deprecate code, but this plugin is a hard-dependency of `grails-plugin-rest`, which is distributed with the (non-deprecated) `rest-api` profile. Although this plugin is deprecated, it is broken, and the plugins that depend on it should be considered broken as well.

Registering custom object marshallers breaks things in unexpected ways (as is the case when we render command object validation errors a la `respond cmd.errors`), and this PR should address that. Would you reconsider and make another minor release?

**Comment by jameskleeh** [comment]
@joemccall86 The plugin is not broken. The entire issue is caused by `new RestBuilder`, which has the specific configuration option to skip registration of converters. Why not simply use that option?

**Comment by joemccall86** [comment]
Fair enough. Sorry I called the plugin broken. I can use that option, since registering custom marshallers is officially deprecated, and that's a prerequisite for this bug.

However unsuspecting devs should be aware that the `DefaultJsonRenderer` still uses the converters plugin. Basically, registering custom marshallers will break the default json renderer if `RestBuilder` is initialized anywhere in code with the no-arg constructor. 

I'm unsure how to prevent others from encountering this issue. Maybe have the `RestBuilder` use its own config instead of the one in `ConvertersCofigurationHolder`?

**Comment by jameskleeh** [comment]
@joemccall86 Perhaps some logging could be added to RestBuilder to warn of this possibility

**Comment by graemerocher** [comment]
I have merged the various PRs for Grails 4 we will either have to remove the dependency on this plugin from `grails-plugin-rest` (and use Jackson for example) or release a maintenance release of this plugin and continue with the deprecated scenario that we are in now.

**Comment by graemerocher** [comment]
This PR was reverted due to it causing failing tests in core. Ideally we should no longer use this library in core.

**Pull request merged**
